### ISSUE TITLE
[Question] About rate limits

### ISSUE THREAD

**Issue by Suleman-Elahi** [SlothKun/TwitterAccountBlocking#1]
I have a list of Twitter accounts that I want to block... and I have over a million troll and toxic accounts in CSV. Will this script be able to do that? And how long it will take to block all those users if I use this script? Thanks.

**Comment by SlothKun** [comment]
My script should be able to do that but it'll take a lot of time as the app will sleep when rate limit is exceed (and the rate limit depend on the number of users using the app)
I cannot give you a precise duration but I can say that it took me a lot of time when I tried blocking 250k accounts

I didn't find a way to overcome the rate limit so yeah..
